# RoArm M3 Professional Control Interface
# Configuration File
# Version 3.1.0

# ================================
# ROBOT CONNECTION
# ================================
robot:
  # Serial Connection
  port: "/dev/tty.usbserial-110"  # macOS/Linux
  # port: "COM3"                  # Windows
  baudrate: 115200
  timeout: 1.0
  
  # Connection Options
  auto_connect: true
  retry_attempts: 3
  retry_delay: 2.0
  
  # Simulator Mode
  simulator_mode: false
  simulator_port: "SIMULATOR"

# ================================
# SERVO CONFIGURATION
# ================================
servos:
  # Servo Limits (in radians)
  limits:
    base:     [-3.14159, 3.14159]      # ±180°
    shoulder: [-1.5708, 1.5708]        # ±90°
    elbow:    [-2.0944, 2.0944]        # ±120°
    wrist:    [-1.5708, 1.5708]        # ±90°
    hand:     [-3.14159, 3.14159]      # ±180°
    head:     [-1.0472, 1.0472]        # ±60°
  
  # Speed Limits (rad/s)
  max_speeds:
    base:     1.0
    shoulder: 0.8
    elbow:    1.2
    wrist:    1.5
    hand:     2.0
    head:     1.0
  
  # Default Positions
  home_position:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  scanner_position: [0.0, 0.785, -1.571, -0.785, 0.0, 0.0]  # 45°, -90°, -45°

# ================================
# SAFETY CONFIGURATION
# ================================
safety:
  # Safety Margins (in radians)
  position_margins:    0.087   # 5° margin from limits
  velocity_margins:    0.1     # 10% margin from max speeds
  
  # Collision Detection
  collision_detection: true
  emergency_stop:      true
  soft_limits:         true
  
  # Monitoring
  position_monitoring: true
  temperature_monitoring: false
  current_monitoring:  false
  
  # Emergency Actions
  emergency_action: "stop_and_hold"  # stop_and_hold, return_home, power_off

# ================================
# SCANNER CONFIGURATION
# ================================
scanner:
  # Scanner Type
  type: "structured_light"  # structured_light, laser, photogrammetry
  
  # Field of View (in degrees)
  fov_horizontal: 60
  fov_vertical:   45
  
  # Working Distances (in meters)
  min_distance:     0.08
  max_distance:     0.30
  optimal_distance: 0.15
  
  # Resolution
  resolution:
    horizontal: 1920
    vertical:   1080
  depth_resolution: 0.001  # 1mm
  
  # Timing
  capture_time:    0.5   # seconds per capture
  processing_time: 0.2   # seconds per processing
  settle_time:     0.3   # stabilization time
  
  # Quality Settings
  overlap_percentage: 25  # 25% overlap
  quality_target:     95  # 95% quality target

# ================================
# PATTERN DEFAULTS
# ================================
patterns:
  # Default Pattern Settings
  default_speed:      0.3
  default_settle:     0.5
  default_overlap:    0.2
  
  # Raster Scan Defaults
  raster:
    width:  0.20
    height: 0.15
    rows:   10
    cols:   10
    zigzag: true
  
  # Spiral Scan Defaults
  spiral:
    radius_start: 0.05
    radius_end:   0.15
    revolutions:  4.0
    points_per_rev: 32
  
  # Spherical Scan Defaults
  spherical:
    radius:      0.15
    theta_steps: 12
    phi_steps:   8
  
  # Preset Configurations
  presets:
    quick_preview:
      type: "raster"
      speed: 0.6
      quality: "fast"
      
    high_quality:
      type: "spherical"
      speed: 0.25
      quality: "maximum"
      
    small_object:
      type: "spiral"
      speed: 0.4
      optimal_distance: 0.10
      
    large_object:
      type: "spherical"
      speed: 0.3
      optimal_distance: 0.20

# ================================
# TECHNICAL SCANNING
# ================================
technical:
  # Algorithm Configuration
  default_algorithm: "fibonacci_sphere"
  
  # Technical Parameters
  angular_resolution: 5.0    # degrees
  path_optimization:  "greedy"
  safety_margin:      5.0    # degrees
  
  # Advanced Options
  multi_pass:         false
  adaptive_exposure:  true
  quality_metrics:    true
  
  # Performance Settings
  max_computation_time: 30.0  # seconds
  parallel_processing:  true

# ================================
# CALIBRATION
# ================================
calibration:
  # Auto-Calibration
  auto_calibrate_on_start: false
  calibration_timeout:     300   # seconds
  
  # Calibration Types
  joint_calibration:    true
  scanner_calibration:  true
  system_calibration:   true
  
  # Calibration Accuracy
  position_accuracy:    0.001  # 1mm
  angle_accuracy:       0.017  # 1 degree
  
  # Calibration Points
  calibration_points:   9      # 3x3 grid
  verification_points:  4      # corner verification

# ================================
# LOGGING
# ================================
logging:
  # Log Levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Log Destinations
  console: true
  file:    true
  
  # File Settings
  log_directory: "logs"
  log_filename:  "roarm_{date}.log"
  max_file_size: 10485760  # 10MB
  backup_count:  5
  
  # Debug Settings
  debug_mode:           false
  trace_movements:      false
  log_servo_positions:  false
  performance_logging:  false

# ================================
# FILE PATHS
# ================================
paths:
  # Data Directories
  sequences_dir:    "sequences"
  scans_dir:        "scans"
  calibration_dir:  "calibration"
  logs_dir:         "logs"
  
  # Configuration
  patterns_config:  "patterns/custom"
  presets_config:   "presets"
  
  # Temporary Files
  temp_dir:         "temp"
  cache_dir:        "cache"

# ================================
# PERFORMANCE TUNING
# ================================
performance:
  # Memory Management
  max_memory_usage:   1024  # MB
  cache_enabled:      true
  cache_size:         100   # patterns
  
  # Processing
  max_threads:        4
  async_processing:   true
  
  # Network/Communication
  communication_timeout: 5.0
  retry_timeout:        1.0
  
  # File I/O
  buffer_size:        8192
  compression:        true

# ================================
# USER INTERFACE
# ================================
ui:
  # Terminal Settings
  clear_screen:       true
  colored_output:     true
  progress_bars:      true
  
  # Menu Settings
  auto_refresh:       false
  status_display:     true
  debug_info:         false
  
  # Confirmations
  confirm_movements:  true
  confirm_scans:      false
  confirm_calibration: true

# ================================
# EXPERIMENTAL FEATURES
# ================================
experimental:
  # Advanced Features (Use with caution!)
  machine_learning:   false
  predictive_control: false
  auto_optimization:  false
  
  # Beta Features
  voice_control:      false
  gesture_control:    false
  remote_monitoring:  false
  
  # Development Features
  simulation_mode:    false
  test_patterns:      false
  benchmark_mode:     false

# ================================
# VERSION INFO
# ================================
version:
  config_version: "3.1.0"
  compatible_versions: ["3.0.0", "3.1.0"]
  last_updated: "2025-08-09"
  created_by: "RoArm Professional Team"