≈# RoArm M3 Professional Configuration
# Optimized for macOS M4 with Revopoint Mini2 Scanner

# System Configuration
system:
  port: "/dev/tty.usbserial-110"  # Auto-detect if set to "auto"
  baudrate: 115200
  timeout: 2.0
  debug: false
  auto_connect: true

# Hardware Configuration
hardware:
  # Servo Limits in Radians (based on Waveshare documentation)
  servo_limits:
    base: [-3.14, 3.14]        # ±180° (360° rotation)
    shoulder: [-1.57, 1.57]     # ±90° (180° range)
    elbow: [0.0, 3.14]          # 0-180° (forward only)
    wrist: [-1.57, 1.57]        # ±90° (180° range)
    roll: [-3.14, 3.14]         # ±180° (360° rotation)
    hand: [1.08, 3.14]          # 62°-180° (gripper range)
  
  # Standard Positions
  home_position:
    base: 0.0
    shoulder: 0.0
    elbow: 1.57      # 90°
    wrist: 0.0
    roll: 0.0
    hand: 3.14       # Closed
  
  scanner_position:
    base: 0.0
    shoulder: 0.35   # 20° up
    elbow: 1.22      # 70°
    wrist: -1.57     # 90° down (level scanner)
    roll: 1.57       # 90° for scanner mount
    hand: 2.5        # Secure grip
  
  park_position:
    base: 0.0
    shoulder: -1.57  # Down
    elbow: 3.14      # Folded
    wrist: 0.0
    roll: 0.0
    hand: 3.14       # Closed

# Scanner Configuration (Revopoint Mini2)
scanner:
  model: "Revopoint Mini2"
  weight: 0.2                  # 200g
  mount_offset:
    x: 0.0
    y: 0.0
    z: 0.05                    # 5cm above gripper
  
  # Scanning Parameters
  optimal_distance: 0.15       # 15cm
  min_distance: 0.10          # 10cm
  max_distance: 0.30          # 30cm
  fov_horizontal: 40          # degrees
  fov_vertical: 30            # degrees
  
  # Motion Settings for Scanning
  scan_speed: 0.3             # Slower for stability
  settle_time: 0.5            # Wait after movement
  extra_settle_heavy: 0.2     # Additional wait with scanner

# Motion Control
motion:
  # Speed Settings (factor: 0.1 to 2.0)
  default_speed: 1.0
  speeds:
    very_slow: 0.2
    slow: 0.5
    normal: 1.0
    fast: 1.5
    very_fast: 2.0
    scan: 0.3
    teaching: 0.5
  
  # Acceleration (rad/s²)
  default_acceleration: 2.0
  max_acceleration: 5.0
  scan_acceleration: 1.0      # Gentle for scanning
  
  # Jerk (rad/s³)
  default_jerk: 5.0
  max_jerk: 10.0
  smooth_jerk: 2.0
  
  # Trajectory Profiles
  default_trajectory: "s_curve"
  trajectory_smoothness: 0.7
  
  # Weight Compensation
  enable_weight_compensation: true
  compensation_factors:
    shoulder: 0.05            # per 100g
    elbow: 0.03              # per 100g

# Teaching Mode
teaching:
  # Recording Settings
  sample_rate: 50             # Hz
  position_threshold: 0.01    # rad - minimum change to record
  max_waypoints: 1000
  compression: true
  auto_optimize: true
  
  # Default Parameters
  default_speed: 0.5
  default_acceleration: 1.5
  default_trajectory: "s_curve"
  
  # File Settings
  save_directory: "sequences"
  file_format: "json"
  auto_backup: true

# Scan Patterns
scan_patterns:
  raster:
    width: 0.20               # 20cm
    height: 0.15              # 15cm
    rows: 10
    cols: 10
    overlap: 0.2              # 20%
    zigzag: true
    speed: 0.3
    settle_time: 0.5
  
  spiral:
    radius_start: 0.05        # 5cm
    radius_end: 0.15          # 15cm
    revolutions: 5
    points_per_rev: 36
    continuous: true
    speed: 0.25
    height_range: 0.10        # 10cm
  
  spherical:
    radius: 0.15              # 15cm
    theta_steps: 12           # horizontal
    phi_steps: 8              # vertical
    phi_range: [-60, 60]      # degrees
    speed: 0.3
    settle_time: 0.7
  
  turntable:
    steps: 36                 # 10° increments
    radius: 0.15
    height_levels: 1
    height_range: 0.10
    speed: 0.5
    settle_time: 1.0
  
  cobweb:
    radial_lines: 8
    circles: 5
    max_radius: 0.15
    speed: 0.3

# Safety Settings
safety:
  # Emergency Stop
  emergency_deceleration: 10.0  # rad/s²
  emergency_stop_torque_off: true
  
  # Limits
  collision_margin: 0.02        # 2cm safety margin
  torque_limit: 0.8             # 80% max torque
  
  # Monitoring
  temperature_warning: 50       # °C
  temperature_critical: 60      # °C
  voltage_min: 5.5             # V
  voltage_max: 7.0             # V
  
  # Auto Recovery
  auto_recovery: true
  recovery_attempts: 3
  recovery_delay: 2.0          # seconds

# User Interface
ui:
  # Terminal Settings
  colored_output: true
  progress_bars: true
  emoji_indicators: true
  
  # Feedback
  audio_feedback: false        # macOS sound alerts
  led_feedback: true          # RoArm LED indicators
  
  # Display
  decimal_places: 3
  angle_units: "radians"      # or "degrees"
  
  # Controls
  manual_step_size: 0.1       # rad per keypress
  speed_increment: 0.1        # speed adjustment step

# Logging
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  file: "roarm_system.log"
  max_size: 10485760         # 10MB
  backup_count: 5
  format: "detailed"          # simple, detailed, json
  
  # Component-specific levels
  components:
    controller: "INFO"
    serial: "WARNING"
    teaching: "INFO"
    scanner: "DEBUG"
    safety: "INFO"

# Advanced Settings
advanced:
  # Serial Communication
  serial_retry_attempts: 3
  serial_retry_delay: 1.0
  command_queue_size: 100
  response_timeout: 0.5
  
  # Threading
  enable_threading: true
  thread_pool_size: 4
  
  # Performance
  trajectory_points: 50       # points per movement
  interpolation_method: "cubic"
  path_optimization: true
  
  # Calibration
  auto_calibration: false
  calibration_speed: 0.2
  calibration_samples: 10
  
  # Network (future expansion)
  enable_network: false
  api_port: 8080
  websocket_port: 8081
