# RoArm Pro Default Configuration
# Copy this file to ~/.roarm_pro/settings.yaml and modify as needed

# Motion Settings
speed_factor: 1.0          # Global speed multiplier (0.1 - 3.0)
acceleration_limit: 2.0    # Maximum acceleration (rad/s²)
settle_time: 0.1          # Time to settle after movement (seconds)

# Scanner Settings  
scanner_mounted: false     # Set to true when scanner is attached
scanner_grip: 2.5         # Default grip position for scanner
scan_speed: 0.5           # Speed factor for scanning operations

# Safety Settings
emergency_stop_enabled: true   # Enable emergency stop functionality
soft_limits_enabled: true      # Enforce joint limits

# UI Settings
language: de              # Interface language (de/en)
debug_mode: false         # Enable debug output
auto_connect: true        # Auto-connect on startup

# Calibration
calibrated: false         # Calibration status
calibration_version: "1.0" # Calibration data version

# Advanced Settings (normally don't change)
min_duration: 0.5         # Minimum movement duration
max_duration: 10.0        # Maximum movement duration
trajectory_points: 50     # Points per trajectory
command_delay: 0.02       # Delay between commands (seconds)
